package parspice.socketManager;

import parspice.sender.Sender;

import java.io.IOException;
import java.io.InputStream;
import java.io.ObjectInputStream;
import java.net.ServerSocket;
import java.util.ArrayList;
import java.util.List;

/**
 * A threadable class that listens on a socket for all responses coming
 * back from a single worker.
 *
 * It aggregates the responses into a list, which is later combined with the
 * lists generated by other workers.
 *
 * @param <O> The type deserialized by the given sender object.
 */
public class OutputSocketManager<O> extends SocketManager<O> {
    private final Sender<O> outputSender;

    /**
     * Creates an instance of OutputSocketManager.
     *
     * @param serverSocket a pre-made socket to interact with
     * @param outputSender a sender for deserializing responses
     * @param workerIndex the unique index of the worker associated with the socket, for error reporting
     * @param batchSize number of outputs to expect
     */
    public OutputSocketManager(ServerSocket serverSocket, Sender<O> outputSender, int workerIndex, int batchSize) {
        super(serverSocket, workerIndex, batchSize);
        this.outputSender = outputSender;
    }

    /**
     * Listens for outputs and aggregates them.
     */
    @Override
    public void sendAndReceive() {
        try {
            ObjectInputStream ois = getInputStream();
            for (int i = 0; i < batchSize; i++) {
                outputs.add(outputSender.read(ois));
            }
            ois.close();
        } catch (IOException e) {
            System.out.println("Socket Manager " + workerIndex + " failed after " + outputs.size());
            e.printStackTrace();
        }
    }
}
